[tool.poetry]
name = "vss365-today-api"
version = "0.1.0"
description = ""
authors = ["Caleb Ely <le717@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
webargs = "^6.0.0"
flask = "^1.1.1"
python-dotenv = "^0.12.0"
gunicorn = "20.0.4"
pyjwt = "^1.7.1"
records = "^0.5.3"
pymysql = "^0.9.3"
Flask-Cors = "^3.0.8"
requests = "^2.23.0"
sys-vars = {url = "https://github.com/le717/sys-vars/releases/download/v1.0.0/sys_vars-1.0.0-py3-none-any.whl"}

[tool.poetry.dev-dependencies]
flake8 = "^3.7.9"
mypy = "^0.770"
toml = "^0.10.0"
black = "^19.10b0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
