version: '3.7'

services:
  vss365today-api:
    image: vss365today-api:latest
    container_name: vss365today-api
    restart: unless-stopped
    volumes:
      - ../:/app  # the base directory is one level above here
    ports:
      - 127.0.0.1:5000:5000
    environment:
      - FLASK_ENV=production
      - DOCKER_SECRETS_PATH=/app/secrets
    entrypoint:
      - sh
      - ./run-app.sh
    networks:
      - vss365today

  mariadb:
    image: mariadb:10.4
    container_name: vss365today-db
    restart: unless-stopped
    volumes:
      - ../db:/docker-entrypoint-initdb.d
      - ../secrets:/secrets
      - ../../db:/var/lib/mysql
    ports:
      - 127.0.0.1:3306:3306
    environment:
      - MYSQL_DATABASE=vss365today
      - MYSQL_USER_FILE=/secrets/DB_USERNAME
      - MYSQL_PASSWORD_FILE=/secrets/DB_PASSWORD
      - MYSQL_ROOT_PASSWORD_FILE=/secrets/DB_PASSWORD_ROOT
    networks:
      - vss365today

networks:
  vss365today:
    driver: bridge
